-- AlterTable
ALTER TABLE "Camera" ADD COLUMN     "movementDuration" DOUBLE PRECISION NOT NULL DEFAULT 4,
ADD COLUMN     "movementIntensity" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "movementType" TEXT NOT NULL DEFAULT 'STATIC';
